name = "flyology_remoting"
description = "Transport-neutral message remoting for Flyology tasks"
version = "0.1.0-dev"

authors = ["Yurii Rashkovskii"]
maintainers = ["Yurii Rashkovskii <yrashk@gmail.com>"]
maintainers-logins = ["yrashk"]
licenses = "MIT OR Apache-2.0"
website = "https://github.com/flyology-ada/flyology-remoting"
tags = ["ada", "remoting", "messaging", "ipc", "rpc"]
project-files = ["flyology_remoting.gpr"]

[[depends-on]]
flyology = "=0.1.1-dev"

[[depends-on]]
flyology_wire = "=0.1.0-dev"

[[pins]]
flyology_wire = { url = "https://github.com/flyology-ada/flyology-wire.git", commit = "97dc25218a33a6dabfba9b726239d5daab676128" }

[available.'case(os)']
'linux|macos' = true
'...' = false

[[actions]]
type = "test"
command = ["./scripts/test.sh"]
